name: Check Links

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at 00:00 UTC
  workflow_dispatch:   # Allow manual triggering of the workflow

jobs:
  check_links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.6.1
        with:
          args: --accept 200,429,err,ERR
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue

      - name: Create or update issue
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.TOKEN }}
          issue-number: 12
          body: |
            ## :warning: Broken links detected

            The following broken links were found in the Markdown files:

            ```
            ${{ steps.check_links.outputs.stdout }}
            ```

            Please fix these broken links as soon as possible.
